# Default values for conquer-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# All properties can be found here https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#general-parameters
fullnameOverride: "argocd"

configs:
  params:
    server.insecure: true # Run server without TLS, this will allow TLS termination at the nginx ingress controller https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-ssl-termination-at-ingress-controller
    # Value for base href in index.html. Since Argo CD is running behind reverse proxy under subpath different from /
    # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
    server.basehref: "/argocd"
    # server.rootpath: /argocd Alternative to using the rewrite-target in the ingress-controller https://github.com/argoproj/argo-helm/blob/804af65b38dd1c4a27a3df5fb478d18c126a6e24/charts/argo-cd/values.yaml#L246
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    ingressClassName: "nginx"
    paths:
      # The first request to ArgoCD will return its index.html with the baseref modified 
      # https://<load-balancer>/argocd -> https://<load-balancer>/ | HTTP 200 index.html
      # Then the browser will load the scripts and assets using /argocd that will be also rewrite
      # Example
      # /argocd/main.js -> /main.js
      - /argocd(/|$)(.*)
    pathType: ImplementationSpecific
    https: false
