# -- Deploy Argo CD Applications within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/

applications:
- name: nginx-controller
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.8.3
      chart: ingress-nginx
      helm:
        valueFiles:
        - $values/charts-overrides/nginx-controller/values.yaml
    - repoURL: https://github.com/conquer-project/helm-charts.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-tools
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true

- name: metrics-server
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.11.0
    chart: metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-tools
  syncPolicy:
    automated:
      prune: true       # will delete resources when Argo CD detects the resource is no longer defined in Git
      selfHeal: false   # TODO: Change to True later. Git repo will always be the source of truth (any manual change on k8s will be overwritten)
      allowEmpty: false # do not allow argo applications have empty resource
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true

- name: sealed-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.13.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-tools
  syncPolicy:
    automated:
      prune: true       # will delete resources when Argo CD detects the resource is no longer defined in Git
      selfHeal: false   # TODO: Change to True later. Git repo will always be the source of truth (any manual change on k8s will be overwritten)
      allowEmpty: false # do not allow argo applications have empty resource
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true